SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_INS as AI
JOIN ANIMAL_OUTS as AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE != AO.SEX_UPON_OUTCOME AND
        AI.SEX_UPON_INTAKE LIKE 'Intact%'


SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_INS as AI
JOIN ANIMAL_OUTS as AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%' AND (
    AO.SEX_UPON_OUTCOME LIKE 'Spayed%' | or AO.SEX_UPON_OUTCOME LIKE 'Neutered%'
    )